/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/hello": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** A greeting, and the proof that the two apps can talk. */
        get: operations["AppController_getHello"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create an account and send its login link.
         * @description An address that already exists is sent a link instead of being duplicated. If that account was never verified, these onboarding values overwrite the stashed ones.
         */
        post: operations["AuthController_register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login-link": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send a login link to an existing account.
         * @description An unknown address creates nothing and is sent nothing; only the response is identical. Every login link therefore belongs to a real user.
         */
        post: operations["AuthController_requestLoginLink"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Spend a login link and start a session.
         * @description First verification of an account also provisions its database, writes the profile the registration form described, and seeds the picked starter categories; a returning user just gets a session. **409** is the one actionable rejection: the link was replaced by a newer one, so the most recent email is the one to open. Every other dead token - unknown, expired, already spent, or belonging to a deleted account - is a 401.
         */
        post: operations["AuthController_verify"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The identity behind a session token.
         * @description The central directory holds an email and a database pointer, so that is all this answers. Names, currency and budget live in the profile, which is its own endpoint.
         */
        get: operations["AuthController_getSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HelloResponseDto: {
            message: string;
        };
        RegisterDto: {
            /**
             * @description Major units (e.g. 2000.50). Stored as integer cents. The cap is not a
             *     product judgment: it keeps the cents conversion far inside JS safe-integer
             *     range while staying generous for zero-decimal currencies, whose budgets
             *     carry many digits.
             */
            monthlyBudget: number;
            firstName: string;
            lastName: string;
            /** Format: email */
            email: string;
            currency?: string;
            /** @description Capped at 28 so the day exists in every month. */
            monthStartDay?: number;
            /**
             * @description The starter chips picked on screen 03, by name.
             *
             *     Required but allowed to be empty: A4 records that no minimum is enforced,
             *     and a user who deselects everything is making a valid choice. Required
             *     rather than optional so a frontend that stops sending the field fails
             *     loudly instead of silently seeding nothing.
             */
            categories: ("Groceries" | "Dining out" | "Transport" | "Shopping" | "Housing" | "Health" | "Entertainment" | "Bills" | "Subscriptions" | "Other")[];
        };
        ErrorResponseDto: {
            /** @description String for most errors; an array for class-validator's field messages. */
            message: string | string[];
            statusCode: number;
            error: string;
            timestamp: string;
            path: string;
        };
        RequestLoginLinkDto: {
            /** Format: email */
            email: string;
        };
        VerifyLoginLinkDto: {
            /**
             * @description The raw token, exactly as it arrived in the link. 43 characters in practice
             *     (256 bits, base64url); the bound is loose enough not to encode that here
             *     while still keeping a megabyte body from ever reaching a hash function.
             */
            token: string;
        };
        VerifyResponseDto: {
            /**
             * @description The raw session token, to be sent back as `Authorization: Bearer <token>`.
             *
             *     The only place it ever appears in a response - the server keeps its hash.
             *     The frontend puts it in an httpOnly, first-party cookie and forwards it
             *     server-side; it must never reach client-side JavaScript.
             */
            token: string;
            /** @description ISO 8601. Fixed at issue: using the session does not extend it. */
            expiresAt: string;
        };
        SessionResponseDto: {
            userId: string;
            email: string;
            /** @description ISO 8601, the same instant verification returned. */
            expiresAt: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AppController_getHello: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HelloResponseDto"];
                };
            };
        };
    };
    AuthController_register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterDto"];
            };
        };
        responses: {
            /** @description Accepted. The body is always empty and the response is byte-for-byte identical whether or not an account exists for the submitted address - that is the enumeration defense (REG-6, LOG-6), not an unfinished response. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation failed. `message` is the array of field errors produced by the global ValidationPipe. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Rate limited. Refused by the throttler guard, which runs before the request body is ever validated. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    AuthController_requestLoginLink: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequestLoginLinkDto"];
            };
        };
        responses: {
            /** @description Accepted. The body is always empty and the response is byte-for-byte identical whether or not an account exists for the submitted address - that is the enumeration defense (REG-6, LOG-6), not an unfinished response. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation failed. `message` is the array of field errors produced by the global ValidationPipe. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Rate limited. Refused by the throttler guard, which runs before the request body is ever validated. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    AuthController_verify: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyLoginLinkDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VerifyResponseDto"];
                };
            };
            /** @description Validation failed. `message` is the array of field errors produced by the global ValidationPipe. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Not authenticated. The bearer credential is missing, invalid, expired or already spent. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description The request conflicts with the current state. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Rate limited. Refused by the throttler guard, which runs before the request body is ever validated. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    AuthController_getSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponseDto"];
                };
            };
            /** @description Not authenticated. The bearer credential is missing, invalid, expired or already spent. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
}
