/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness check: constant 200, no auth, no database. */
        get: operations["AppController_getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/templates/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The starter categories onboarding offers.
         * @description Public, because onboarding step 2 runs before an account exists. Send the `id`s of the picked entries as `RegisterDto.categories`; each picked template becomes one of the account’s categories at verification, carrying this `name`, `color`, `icon` and `description` (as the category’s `note`). The order is the one to render.
         */
        get: operations["TemplatesController_categories"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/templates/palette": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The colours and icons a category may be given.
         * @description What the create and edit category picker offers, with the label to show for each. This is what an admin currently has **enabled**, which can be a strict subset of what `POST /api/categories` accepts - a category already carrying a since-disabled colour keeps working.
         */
        get: operations["TemplatesController_palette"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create an account and send its login link.
         * @description An address that already exists is sent a link instead of being duplicated. If that account was never verified, these onboarding values overwrite the stashed ones.
         */
        post: operations["AuthController_register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login-link": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send a login link to an existing account.
         * @description An unknown address creates nothing and is sent nothing; only the response is identical. Every login link therefore belongs to a real user.
         */
        post: operations["AuthController_requestLoginLink"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Spend a login link and start a session.
         * @description First verification of an account also provisions its database, writes the profile the registration form described, and seeds the picked starter categories; a returning user just gets a session. **409** is the one actionable rejection: the link was replaced by a newer one, so the most recent email is the one to open. Every other dead token - unknown, expired, already spent, or belonging to a deleted account - is a 401.
         */
        post: operations["AuthController_verify"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The identity behind a session token.
         * @description The central directory holds an email and a database pointer, so that is all this answers. Names, currency and budget live in the profile, which is its own endpoint.
         */
        get: operations["AuthController_getSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The signed-in person and their preferences.
         * @description `email` comes from the central directory, everything else from your own database. `monthlyBudget` is in major units (2000.50, not 200050) and `monthStartDay` is the day of the month your budgeting period starts on.
         */
        get: operations["ProfileController_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Change your details or preferences.
         * @description Send only the fields to change: an absent field is left alone, and no field accepts null - every one of them is required in storage. An empty body is a **400**. `monthlyBudget` is in major units. Changing `email` changes where future login links are sent; links already in flight to the old address keep working, and your current session is unaffected. **409** means the address belongs to another account.
         */
        patch: operations["ProfileController_update"];
        trace?: never;
    };
    "/api/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List transactions.
         * @description Every filter is optional. `period` defaults to `current`, so a call with no query string returns **this budgeting period only**, which is the view TRN-3 draws; pass `period=all` for history. `total` counts matches after filters - read it rather than the array length. There is no pagination: the whole filtered set comes back and the table scrolls.
         */
        get: operations["TransactionsController_list"];
        put?: never;
        /**
         * Record a transaction.
         * @description `amount` is in major units (12.50, not 1250) and must be positive. `date` is a calendar date, `YYYY-MM-DD`, stored verbatim - backdating is supported and puts the transaction in the month that date falls in. **404** means the `categoryId` in the body names no category of yours.
         */
        post: operations["TransactionsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/transactions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * One transaction, with the context frame 08 draws around it.
         * @description Carries two extras on **different windows**, deliberately. `category` is that category's progress for the **current** period, even when this transaction is from an earlier one - the bar answers where the category stands now. `recentInCategory` is the latest transactions in the same category from **any** month, excluding this one. **404** here always means the id in the URL. Expect `category.status` to be `uncapped` most of the time: caps are optional and the preselected fallback has none.
         */
        get: operations["TransactionsController_detail"];
        put?: never;
        post?: never;
        /**
         * Delete a transaction.
         * @description Permanent as far as this API is concerned: the transaction stops existing through every endpoint. Deleting one twice is a **404**, and **404** here always means the id in the URL.
         */
        delete: operations["TransactionsController_remove"];
        options?: never;
        head?: never;
        /**
         * Change a transaction.
         * @description Send only the fields to change: an absent field is left alone, and `note` accepts null to clear it. An empty body is a **400**, because it would record an edit that changed nothing. **404** means either the id in the URL or a `categoryId` in the body names nothing of yours.
         */
        patch: operations["TransactionsController_update"];
        trace?: never;
    };
    "/api/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Your categories with this period’s progress, and the allocation summary.
         * @description One call serves the whole screen. Money is in major units. `spent` and `transactionCount` cover the current budgeting period, which starts on your profile’s `monthStartDay` rather than the 1st. An uncapped category reports `status: "uncapped"` with a null cap, percent, remaining and over - a cap is optional, so this is ordinary rather than exceptional. `allocation.unallocated` can be negative when caps exceed the budget.
         */
        get: operations["CategoriesController_list"];
        put?: never;
        /**
         * Add a category.
         * @description `monthlyCap` is optional: omit it for a category with no limit. A cap of **0 or less is a 400** - it means "spend nothing here", which is not the same as no limit and is almost always an empty field rather than an intent.
         */
        post: operations["CategoriesController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/categories/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete a category, keeping its transactions.
         * @description The transactions are **not** deleted: they move to `Uncategorized`, which is why that category exists. **409** means you tried to delete `Uncategorized` itself.
         */
        delete: operations["CategoriesController_remove"];
        options?: never;
        head?: never;
        /**
         * Change a category.
         * @description Send only the fields to change. An absent field is left alone; `monthlyCap` and `note` also accept `null`, which clears them - clearing a cap makes the category uncapped. An empty body is a **400**. **409** means you tried to rename `Uncategorized`, whose name is fixed; its cap, color, icon and note are all editable.
         */
        patch: operations["CategoriesController_update"];
        trace?: never;
    };
    "/api/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Every figure the dashboard draws, for the current period.
         * @description `remaining` and the weekly buckets can imply overspending; nothing here is clamped. `insight` is the latest insight set’s headline and body, or null when none has been generated. An account with no transactions this period returns zeroes, an empty weekly series, no categories and no top category rather than failing.
         */
        get: operations["DashboardController_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/insights": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Your latest insight set, with the state to render it in.
         * @description One call serves the whole screen in all three states. `state` is `empty` before anything has generated, `generating` while a run is in flight (render skeletons), or `ready` when a set is available. The content fields always carry the most recent **ready** set, independent of `state`, so a regenerate shows skeletons while the dashboard teaser keeps its last-good content. A failed run is invisible: the previous ready set stays returned.
         */
        get: operations["InsightsController_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/insights/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start generating a fresh insight set.
         * @description Asynchronous: this returns **202** as soon as the run is registered, and the set is produced in the background. Poll `GET /api/insights` and render skeletons while `state` is `generating`; the new set replaces the old one when it finishes. A **409** means a run is already in flight - regenerate is disabled until it ends. An account with no transactions produces no set and stays in the empty state.
         */
        post: operations["InsightsController_generate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthResponseDto: {
            status: string;
        };
        CategoryTemplateDto: {
            /**
             * Format: uuid
             * @description What `RegisterDto.categories` takes. Not a category id - the account does not exist yet.
             */
            id: string;
            /**
             * @description Sentence case: first letter capital, everything else lower. Admin-authored, so this is a plain string rather than an enum.
             * @example Dining out
             */
            name: string;
            /**
             * @description A daisyUI semantic colour token, which is what `categories.color` stores. Not a hex: `primary` is valued differently per theme, so several of these have no single hex value.
             * @example secondary
             * @enum {string}
             */
            color: "primary" | "primary-content" | "secondary" | "secondary-content" | "accent" | "accent-content" | "neutral" | "neutral-content" | "info" | "info-content" | "success" | "success-content" | "warning" | "warning-content" | "error" | "error-content" | "base-content/50";
            /**
             * @description A lucide icon name, in lucide’s own kebab-case.
             * @example utensils
             * @enum {string}
             */
            icon: "shopping-basket" | "utensils" | "car" | "zap" | "heart-pulse" | "tv" | "graduation-cap" | "plane" | "scissors" | "gift" | "paw-print" | "landmark" | "circle-question-mark" | "coffee" | "beer" | "pizza" | "ice-cream-cone" | "fuel" | "bus" | "panda" | "bike" | "square-parking" | "house" | "bird" | "waves-horizontal" | "wifi" | "smartphone" | "trash-2" | "wrench" | "sofa" | "pill" | "stethoscope" | "dumbbell" | "eye" | "tag" | "shirt" | "package" | "gem" | "scale" | "credit-card" | "piggy-bank" | "shopping-cart" | "percent" | "receipt" | "trending-up" | "shield" | "gamepad-2" | "music" | "film" | "ticket" | "book" | "camera" | "palette" | "briefcase" | "pencil" | "fish" | "baby" | "users" | "rabbit" | "sailboat" | "tree-palm" | "key-round" | "tent" | "heart";
            /**
             * @description Copied into the user’s own `note` when the category is seeded, after which it is theirs. Editing the template later does not reach back into existing accounts.
             * @example Restaurants, coffee shops, takeout, delivery, and fast food.
             */
            description: string;
        };
        CategoryTemplatesResponseDto: {
            /** @description The enabled category templates, in the order onboarding draws its chips. The order is part of the contract: render them as given rather than sorting. */
            categories: components["schemas"]["CategoryTemplateDto"][];
        };
        PaletteColourDto: {
            /**
             * @description What to send as a category’s `color`.
             * @example accent-content
             * @enum {string}
             */
            token: "primary" | "primary-content" | "secondary" | "secondary-content" | "accent" | "accent-content" | "neutral" | "neutral-content" | "info" | "info-content" | "success" | "success-content" | "warning" | "warning-content" | "error" | "error-content" | "base-content/50";
            /**
             * @description What to show beside it.
             * @example Pine
             */
            label: string;
        };
        PaletteIconDto: {
            /**
             * @description What to send as a category’s `icon`.
             * @example paw-print
             * @enum {string}
             */
            name: "shopping-basket" | "utensils" | "car" | "zap" | "heart-pulse" | "tv" | "graduation-cap" | "plane" | "scissors" | "gift" | "paw-print" | "landmark" | "circle-question-mark" | "coffee" | "beer" | "pizza" | "ice-cream-cone" | "fuel" | "bus" | "panda" | "bike" | "square-parking" | "house" | "bird" | "waves-horizontal" | "wifi" | "smartphone" | "trash-2" | "wrench" | "sofa" | "pill" | "stethoscope" | "dumbbell" | "eye" | "tag" | "shirt" | "package" | "gem" | "scale" | "credit-card" | "piggy-bank" | "shopping-cart" | "percent" | "receipt" | "trending-up" | "shield" | "gamepad-2" | "music" | "film" | "ticket" | "book" | "camera" | "palette" | "briefcase" | "pencil" | "fish" | "baby" | "users" | "rabbit" | "sailboat" | "tree-palm" | "key-round" | "tent" | "heart";
            /** @example Paw */
            label: string;
        };
        PaletteResponseDto: {
            /** @description In admin order. */
            colors: components["schemas"]["PaletteColourDto"][];
            /** @description In admin order. */
            icons: components["schemas"]["PaletteIconDto"][];
        };
        ErrorResponseDto: {
            /** @description String for most errors; an array for class-validator's field messages. */
            message: string | string[];
            statusCode: number;
            error: string;
            timestamp: string;
            path: string;
        };
        RegisterDto: {
            /**
             * @description ISO 4217 code, e.g. `EUR`. Case-insensitive on the way in, stored and returned uppercase.
             * @example EUR
             */
            currency?: string;
            /**
             * @description Major units (e.g. 2000.50). Stored as integer cents. The cap is not a
             *     product judgment: it keeps the cents conversion far inside JS safe-integer
             *     range while staying generous for zero-decimal currencies, whose budgets
             *     carry many digits.
             */
            monthlyBudget: number;
            /** @description Capped at 28 so the day exists in every month. */
            monthStartDay?: number;
            /** @description Ids from `GET /api/templates/categories`. May be empty. Unknown ids are a 400. */
            categories: string[];
            firstName: string;
            lastName: string;
            /** Format: email */
            email: string;
        };
        RequestLoginLinkDto: {
            /** Format: email */
            email: string;
        };
        VerifyLoginLinkDto: {
            /**
             * @description The raw token, exactly as it arrived in the link. 43 characters in practice
             *     (256 bits, base64url); the bound is loose enough not to encode that here
             *     while still keeping a megabyte body from ever reaching a hash function.
             */
            token: string;
        };
        VerifyResponseDto: {
            /**
             * @description The raw session token, to be sent back as `Authorization: Bearer <token>`.
             *
             *     The only place it ever appears in a response - the server keeps its hash.
             *     The frontend puts it in an httpOnly, first-party cookie and forwards it
             *     server-side; it must never reach client-side JavaScript.
             */
            token: string;
            /** @description ISO 8601. Fixed at issue: using the session does not extend it. */
            expiresAt: string;
        };
        SessionResponseDto: {
            userId: string;
            email: string;
            /** @description ISO 8601, the same instant verification returned. */
            expiresAt: string;
        };
        ProfileResponseDto: {
            /**
             * @description Day of the month the budgeting period starts on, 1-28. Every period-scoped
             *     read derives its month window from this at query time, so changing it
             *     re-buckets history rather than rewriting anything.
             */
            monthStartDay: number;
            firstName: string;
            lastName: string;
            /** @description The login identifier. Lives in the central directory, not the profile row. */
            email: string;
            /** @description ISO 4217 code, uppercase. Display only - amounts are stored in minor units. */
            currency: string;
            /** @description Major units (e.g. 2000.5). Stored as integer cents; converted on the way out. */
            monthlyBudget: number;
        };
        UpdateProfileDto: {
            /**
             * @description ISO 4217 code, e.g. `EUR`. Case-insensitive on the way in, stored and returned uppercase.
             * @example EUR
             */
            currency?: string;
            /** @description Major units (e.g. 2000.50), as at registration. Stored as integer cents. */
            monthlyBudget?: number;
            /** @description Capped at 28 so the day exists in every month. */
            monthStartDay?: number;
            firstName?: string;
            lastName?: string;
            /**
             * Format: email
             * @description The login identifier. Changing it changes where future login links are sent
             *     (AC6); links already in flight to the old address keep working.
             */
            email?: string;
        };
        TransactionResponseDto: {
            id: string;
            merchant: string;
            categoryId: string;
            /** @description Major units (e.g. 12.5). Stored as integer cents; converted on the way out. */
            amount: number;
            /** @description `YYYY-MM-DD`, exactly the string that was stored. */
            date: string;
            /** @description Null when the transaction has no note, never absent. */
            note: string | null;
            /** @description ISO 8601. */
            createdAt: string;
            /**
             * @description ISO 8601. Within a millisecond of `createdAt` until the first edit, not
             *     necessarily equal to it: the two columns default from independent `new Date()`
             *     calls, so an insert can straddle a millisecond boundary. Do not use equality
             *     of the two to mean "never edited".
             */
            updatedAt: string;
        };
        TransactionsResponseDto: {
            /** @description Every matching transaction, in the requested sort order. */
            transactions: components["schemas"]["TransactionResponseDto"][];
            /** @description Matches after every filter, not the account total. Equal to `transactions.length` while there is no pagination; read this rather than the array length, so a future page size cannot silently turn the badge into a page count. */
            total: number;
        };
        CategoryResponseDto: {
            /** Format: uuid */
            id: string;
            /** @example Groceries */
            name: string;
            /**
             * @description A daisyUI semantic colour token, not a hex - several of these have no single hex value, being themed per light and dark.
             * @example success
             * @enum {string}
             */
            color: "primary" | "primary-content" | "secondary" | "secondary-content" | "accent" | "accent-content" | "neutral" | "neutral-content" | "info" | "info-content" | "success" | "success-content" | "warning" | "warning-content" | "error" | "error-content" | "base-content/50";
            /**
             * @description Nullable because the column is, not because a new category may omit one:
             *     `CreateCategoryDto.icon` is required as of PET-64 and `UpdateCategoryDto`
             *     cannot clear it, so only a row predating that can be null.
             * @enum {string|null}
             */
            icon: "shopping-basket" | "utensils" | "car" | "zap" | "heart-pulse" | "tv" | "graduation-cap" | "plane" | "scissors" | "gift" | "paw-print" | "landmark" | "circle-question-mark" | "coffee" | "beer" | "pizza" | "ice-cream-cone" | "fuel" | "bus" | "panda" | "bike" | "square-parking" | "house" | "bird" | "waves-horizontal" | "wifi" | "smartphone" | "trash-2" | "wrench" | "sofa" | "pill" | "stethoscope" | "dumbbell" | "eye" | "tag" | "shirt" | "package" | "gem" | "scale" | "credit-card" | "piggy-bank" | "shopping-cart" | "percent" | "receipt" | "trending-up" | "shield" | "gamepad-2" | "music" | "film" | "ticket" | "book" | "camera" | "palette" | "briefcase" | "pencil" | "fish" | "baby" | "users" | "rabbit" | "sailboat" | "tree-palm" | "key-round" | "tent" | "heart" | null;
            note: string | null;
            /** @description True for the one `Uncategorized` category every account has. It cannot be deleted or renamed, deleting any other category moves its transactions here, and the transaction form preselects it. */
            isFallback: boolean;
            /** @description Major units. Null means uncapped, which is not a cap of 0. */
            monthlyCap: number | null;
            /** @description Major units spent in this category during the current period. On the fallback (`isFallback`) row this also carries spend whose category no longer exists, so these figures always sum to the period total; see `transactionCount` for what that costs. */
            spent: number;
            /** @description Transactions counted in `spent`. On the fallback (`isFallback`) row this can exceed what `GET /transactions?categoryId=<this id>` returns: orphaned transactions are attributed here on read but still store the id of the deleted category, so they are counted and not enumerable. Do not present this count as a link to a filtered list for that one row. */
            transactionCount: number;
            /** @description Percentage of the cap used, unrounded. Null when uncapped. Round it for display; the status is decided on cents, so rounding cannot disagree with it. */
            percentUsed: number | null;
            /** @description Major units still available. Null when uncapped or already over; `over` carries the excess instead. */
            remaining: number | null;
            /** @description Major units spent beyond the cap. Null unless the status is `over`. */
            over: number | null;
            /**
             * @description Decided on cents, not on `percentUsed`. `uncapped` when there is no cap.
             * @enum {string}
             */
            status: "on_track" | "near" | "full" | "over" | "uncapped";
        };
        TransactionDetailResponseDto: {
            transaction: components["schemas"]["TransactionResponseDto"];
            /** @description The transaction's category with its stats for the **current** period - not the period the transaction itself falls in. The bar answers where this category stands now. */
            category: components["schemas"]["CategoryResponseDto"];
            /** @description Up to 5 other transactions in the same category, newest first, from any month. Excludes the one in `transaction`. */
            recentInCategory: components["schemas"]["TransactionResponseDto"][];
        };
        CreateTransactionDto: {
            /**
             * @description Major units (e.g. 12.50), stored as integer cents. Positive: this app
             *     records spending, and direction is not a per-row choice.
             */
            amount: number;
            /**
             * Format: date
             * @description The calendar day the money was spent, `YYYY-MM-DD`. Stored verbatim.
             *
             *     Backdating is ordinary and supported: the month a transaction belongs to is
             *     derived from this at read time, so a date in a past month lands in that
             *     month rather than the one it was entered in.
             * @example 2026-08-03
             */
            date: string;
            merchant: string;
            /**
             * Format: uuid
             * @description An existing category of this user's. An unknown id is a 404, not a 400.
             */
            categoryId: string;
            note?: string;
        };
        UpdateTransactionDto: {
            /** @description Major units, as on create. */
            amount?: number;
            /**
             * Format: date
             * @description `YYYY-MM-DD`, as on create. Inline regex for the `pattern` lift.
             * @example 2026-08-03
             */
            date?: string;
            /**
             * @description The one nullable field, and so the one that keeps `@IsOptional()`: null is
             *     a meaningful value here rather than a mistake, and it means "clear the
             *     note".
             */
            note?: string | null;
            merchant?: string;
            /** Format: uuid */
            categoryId?: string;
        };
        AllocationResponseDto: {
            /** @description Major units, from your profile. */
            monthlyBudget: number;
            /** @description Major units. The sum of every live category cap; uncapped categories contribute nothing, so this can sit well below the budget for someone who caps little. */
            allocated: number;
            /** @description Major units, `monthlyBudget - allocated`. **Can be negative**: nothing prevents caps from exceeding the budget (A43), and the figure is returned unclamped so the excess is recoverable. */
            unallocated: number;
        };
        CategoriesResponseDto: {
            /** @description Live categories, ordered by name. */
            categories: components["schemas"]["CategoryResponseDto"][];
            allocation: components["schemas"]["AllocationResponseDto"];
        };
        CreateCategoryDto: {
            /**
             * @description A daisyUI semantic colour token, not a hex.
             *
             *     **Hex was not merely indirect here, it was incoherent.** `primary` is the
             *     one token daisyUI values differently per theme, so Entertainment
             *     (`#422ad5` light, `#605dff` dark) and Education (`#e0e7ff`, `#edf1fe`) have
             *     no single hex value at all - a stored one would record one and paint the
             *     other half the time. The token is the stable identity; the theme resolves
             *     the hue.
             *
             *     `GET /api/templates/palette` is what a picker offers, and it can be a
             *     strict subset of this list: `enabled` is presentation and this is
             *     validation, so a category carrying a since-disabled colour still saves.
             * @example success
             * @enum {string}
             */
            color: "primary" | "primary-content" | "secondary" | "secondary-content" | "accent" | "accent-content" | "neutral" | "neutral-content" | "info" | "info-content" | "success" | "success-content" | "warning" | "warning-content" | "error" | "error-content" | "base-content/50";
            /** @description Major units (e.g. 400.00), stored as integer cents. Omit for no cap. */
            monthlyCap?: number;
            /**
             * @description A lucide icon name, and **required** as of PET-64.
             *
             *     It was `@IsString() @MaxLength(60)` and optional, which accepted `cup` and
             *     `box` - neither of which is a lucide name, so neither could ever render.
             *     Narrowing it to the allowlist is what makes `Record<IconName, LucideIcon>`
             *     on the frontend an exhaustiveness proof, and requiring it is free now and
             *     expensive later.
             *
             *     The column stays **nullable**, deliberately: tightening `categories.icon`
             *     to NOT NULL would be the one user-scope migration in this whole change, and
             *     `backend/src/database/CLAUDE.md` is explicit that such a migration runs
             *     unattended against live data one user at a time. The DTO is what enforces
             *     the invariant going forward.
             * @example shopping-basket
             * @enum {string}
             */
            icon: "shopping-basket" | "utensils" | "car" | "zap" | "heart-pulse" | "tv" | "graduation-cap" | "plane" | "scissors" | "gift" | "paw-print" | "landmark" | "circle-question-mark" | "coffee" | "beer" | "pizza" | "ice-cream-cone" | "fuel" | "bus" | "panda" | "bike" | "square-parking" | "house" | "bird" | "waves-horizontal" | "wifi" | "smartphone" | "trash-2" | "wrench" | "sofa" | "pill" | "stethoscope" | "dumbbell" | "eye" | "tag" | "shirt" | "package" | "gem" | "scale" | "credit-card" | "piggy-bank" | "shopping-cart" | "percent" | "receipt" | "trending-up" | "shield" | "gamepad-2" | "music" | "film" | "ticket" | "book" | "camera" | "palette" | "briefcase" | "pencil" | "fish" | "baby" | "users" | "rabbit" | "sailboat" | "tree-palm" | "key-round" | "tent" | "heart";
            name: string;
            /** @description Captured, but surfaces on no screen today (CED-4, A42). */
            note?: string;
        };
        UpdateCategoryDto: {
            /**
             * @description A daisyUI semantic colour token. See `CreateCategoryDto.color`.
             * @example success
             * @enum {string}
             */
            color?: "primary" | "primary-content" | "secondary" | "secondary-content" | "accent" | "accent-content" | "neutral" | "neutral-content" | "info" | "info-content" | "success" | "success-content" | "warning" | "warning-content" | "error" | "error-content" | "base-content/50";
            /** @description Major units. `null` clears the cap, leaving the category uncapped. */
            monthlyCap?: number | null;
            /**
             * @description A lucide icon name. Not clearable - see the class comment.
             * @example shopping-basket
             * @enum {string}
             */
            icon?: "shopping-basket" | "utensils" | "car" | "zap" | "heart-pulse" | "tv" | "graduation-cap" | "plane" | "scissors" | "gift" | "paw-print" | "landmark" | "circle-question-mark" | "coffee" | "beer" | "pizza" | "ice-cream-cone" | "fuel" | "bus" | "panda" | "bike" | "square-parking" | "house" | "bird" | "waves-horizontal" | "wifi" | "smartphone" | "trash-2" | "wrench" | "sofa" | "pill" | "stethoscope" | "dumbbell" | "eye" | "tag" | "shirt" | "package" | "gem" | "scale" | "credit-card" | "piggy-bank" | "shopping-cart" | "percent" | "receipt" | "trending-up" | "shield" | "gamepad-2" | "music" | "film" | "ticket" | "book" | "camera" | "palette" | "briefcase" | "pencil" | "fish" | "baby" | "users" | "rabbit" | "sailboat" | "tree-palm" | "key-round" | "tent" | "heart";
            note?: string | null;
            name?: string;
        };
        TopCategoryDto: {
            /** Format: uuid */
            id: string;
            /** @example Groceries */
            name: string;
            /**
             * @description A daisyUI semantic colour token, not a hex.
             * @example success
             * @enum {string}
             */
            color: "primary" | "primary-content" | "secondary" | "secondary-content" | "accent" | "accent-content" | "neutral" | "neutral-content" | "info" | "info-content" | "success" | "success-content" | "warning" | "warning-content" | "error" | "error-content" | "base-content/50";
            /** @description Major units spent in this category during the current period. */
            spent: number;
        };
        WeeklyBucketDto: {
            /** @description `YYYY-MM-DD`, inclusive. */
            startDate: string;
            /** @description `YYYY-MM-DD`, exclusive. The final bucket in a period is short - `endDate` is the period end, not seven days after `startDate`. */
            endDate: string;
            /** @description Major units spent within this bucket. */
            total: number;
        };
        DashboardCategoryDto: {
            /** Format: uuid */
            id: string;
            /** @example Groceries */
            name: string;
            /**
             * @description A daisyUI semantic colour token, not a hex.
             * @example success
             * @enum {string}
             */
            color: "primary" | "primary-content" | "secondary" | "secondary-content" | "accent" | "accent-content" | "neutral" | "neutral-content" | "info" | "info-content" | "success" | "success-content" | "warning" | "warning-content" | "error" | "error-content" | "base-content/50";
            /**
             * @description **Here for the recent-transactions card, not for the donut.**
             *
             *     The donut's slices are bare colour and need none. `RecentTransactionsCard`
             *     draws the same `size-9` tile the transactions table does, and joins it off
             *     this array rather than making a second request - see `backend/CLAUDE.md`'s
             *     note on why that join is free. Without this field that tile is the one
             *     place left drawing a placeholder mark for every category, which is exactly
             *     what the close colour pairs cannot survive.
             * @enum {string|null}
             */
            icon: "shopping-basket" | "utensils" | "car" | "zap" | "heart-pulse" | "tv" | "graduation-cap" | "plane" | "scissors" | "gift" | "paw-print" | "landmark" | "circle-question-mark" | "coffee" | "beer" | "pizza" | "ice-cream-cone" | "fuel" | "bus" | "panda" | "bike" | "square-parking" | "house" | "bird" | "waves-horizontal" | "wifi" | "smartphone" | "trash-2" | "wrench" | "sofa" | "pill" | "stethoscope" | "dumbbell" | "eye" | "tag" | "shirt" | "package" | "gem" | "scale" | "credit-card" | "piggy-bank" | "shopping-cart" | "percent" | "receipt" | "trending-up" | "shield" | "gamepad-2" | "music" | "film" | "ticket" | "book" | "camera" | "palette" | "briefcase" | "pencil" | "fish" | "baby" | "users" | "rabbit" | "sailboat" | "tree-palm" | "key-round" | "tent" | "heart" | null;
            /** @description Major units spent in this category during the current period. */
            spent: number;
            /** @description Percentage of the period's total spend this category accounts for, unrounded. Relative to `spent` on this response, not to any cap. Across the whole `categories` array these sum to 100: spend belonging to no live category is folded into the Uncategorized fallback, so every transaction in the period is counted in exactly one entry. Round for display with an apportionment that preserves the total, since rounding each value independently can sum to 99 or 101. */
            percent: number;
        };
        InsightSummaryDto: {
            /** @example You are on track this month */
            headline: string;
            /** @example You've spent $1,240 of your $2,000 budget with 11 days to go. */
            body: string;
        };
        DashboardResponseDto: {
            /** @description Major units spent so far this period. */
            spent: number;
            /** @description Major units, the monthly budget from your profile. */
            monthlyBudget: number;
            /** @description Major units, `monthlyBudget - spent`. Can be negative: overspending is a state the frontend needs the magnitude to draw, the same reasoning as `unallocated` on `GET /api/categories`. */
            remaining: number;
            /** @description Whole days from today to the end of the period, counting today. 1 on the last day of the period, never 0 - the day is not over. */
            daysLeft: number;
            /** @description Live transactions in the current period. */
            transactionCount: number;
            /** @description `spent` divided by days elapsed so far (counting today), not by the days in the whole period - the rate that answers "am I burning too fast", not one that looks better the earlier in the month it is read. */
            averagePerDay: number;
            /** @description The highest-spending category this period, ties broken by name ascending. Null when nothing has been spent yet. */
            topCategory: components["schemas"]["TopCategoryDto"] | null;
            /** @description Sums to `spent`. Anchored to the period start, not to ISO weeks, so the buckets tile the period without gap or overlap; the last one is short rather than overshooting into the next period. An **empty array**, not zero-filled buckets, when there is nothing to chart this period. */
            weeklyBuckets: components["schemas"]["WeeklyBucketDto"][];
            /** @description Every nonzero category this period, percentages unrounded and relative to `spent`. The entries account for all of `spent`, so their `spent` fields sum to it and their `percent` fields sum to 100. Empty when there is no spend yet. */
            categories: components["schemas"]["DashboardCategoryDto"][];
            /** @description Up to 3 most recent transactions in the current period, newest first. */
            recentTransactions: components["schemas"]["TransactionResponseDto"][];
            /** @description The headline and body of the most recently generated insight set, for the teaser card. Null when nothing has been generated yet (including while the first run is still in flight). */
            insight: components["schemas"]["InsightSummaryDto"] | null;
        };
        InsightCardDto: {
            /**
             * @description Maps to the Status palette the frontend draws the card in.
             * @enum {string}
             */
            tone: "warning" | "positive" | "neutral";
            /** @example Dining out is over budget */
            title: string;
            /** @example $312 of $300 - $12 over */
            body: string;
        };
        InsightSetResponseDto: {
            /**
             * @description Whether a run is in flight (`generating`), a completed set exists (`ready`), or nothing has ever generated (`empty`). Independent of the content fields, which always carry the latest `ready` set.
             * @enum {string}
             */
            state: "empty" | "generating" | "ready";
            /**
             * @description The period the latest ready set covers, rendered when it was generated. Null in the empty state.
             * @example October 2025
             */
            monthLabel: string | null;
            /** @description The summary banner of the latest ready set. Null when empty. */
            summary: components["schemas"]["InsightSummaryDto"] | null;
            /** @description The cards of the latest ready set, in their generated order. Empty until a set is ready. */
            insights: components["schemas"]["InsightCardDto"][];
            /** @description ISO 8601, when the latest ready set finished generating. Null when empty. */
            generatedAt: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AppController_getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponseDto"];
                };
            };
        };
    };
    TemplatesController_categories: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryTemplatesResponseDto"];
                };
            };
        };
    };
    TemplatesController_palette: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaletteResponseDto"];
                };
            };
            /** @description Not authenticated. The bearer credential is missing, invalid, expired or already spent. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    AuthController_register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterDto"];
            };
        };
        responses: {
            /** @description Accepted. The body is always empty and the response is byte-for-byte identical whether or not an account exists for the submitted address - that is the enumeration defense (REG-6, LOG-6), not an unfinished response. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation failed. `message` is the array of field errors produced by the global ValidationPipe. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Rate limited. Refused by the throttler guard, which runs before the request body is ever validated. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    AuthController_requestLoginLink: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequestLoginLinkDto"];
            };
        };
        responses: {
            /** @description Accepted. The body is always empty and the response is byte-for-byte identical whether or not an account exists for the submitted address - that is the enumeration defense (REG-6, LOG-6), not an unfinished response. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation failed. `message` is the array of field errors produced by the global ValidationPipe. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Rate limited. Refused by the throttler guard, which runs before the request body is ever validated. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    AuthController_verify: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyLoginLinkDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VerifyResponseDto"];
                };
            };
            /** @description Validation failed. `message` is the array of field errors produced by the global ValidationPipe. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Not authenticated. The bearer credential is missing, invalid, expired or already spent. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description The request conflicts with the current state. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Rate limited. Refused by the throttler guard, which runs before the request body is ever validated. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    AuthController_getSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponseDto"];
                };
            };
            /** @description Not authenticated. The bearer credential is missing, invalid, expired or already spent. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    ProfileController_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileResponseDto"];
                };
            };
            /** @description Not authenticated. The bearer credential is missing, invalid, expired or already spent. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    ProfileController_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProfileDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileResponseDto"];
                };
            };
            /** @description Validation failed. `message` is the array of field errors produced by the global ValidationPipe. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Not authenticated. The bearer credential is missing, invalid, expired or already spent. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description The request conflicts with the current state. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    TransactionsController_list: {
        parameters: {
            query?: {
                /** @description Case-insensitive substring of the merchant name. Trimmed; an empty or whitespace-only term filters nothing. **Case-insensitive for ASCII only** - SQLite `LIKE` does not fold non-ASCII, so a merchant name with diacritics matches only on exact case. */
                search?: string;
                /**
                 * @description One of your categories. An unknown id filters everything out rather than
                 *     404ing - it is a filter, not a resource being addressed.
                 */
                categoryId?: string;
                /** @description Resolved server-side from your `monthStartDay`, so the boundary is your budgeting period rather than the calendar month. `previous` is the period before the current one. `all` applies no date filter. */
                period?: "current" | "previous" | "all";
                /** @description Ties on `date` break on `createdAt` descending, then `id`, so the order is stable across requests rather than reshuffling for no visible reason. */
                sort?: "date_desc" | "date_asc";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionsResponseDto"];
                };
            };
            /** @description Validation failed. `message` is the array of field errors produced by the global ValidationPipe. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Not authenticated. The bearer credential is missing, invalid, expired or already spent. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    TransactionsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTransactionDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionResponseDto"];
                };
            };
            /** @description Validation failed. `message` is the array of field errors produced by the global ValidationPipe. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Not authenticated. The bearer credential is missing, invalid, expired or already spent. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description No such resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    TransactionsController_detail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionDetailResponseDto"];
                };
            };
            /** @description Validation failed. `message` is the array of field errors produced by the global ValidationPipe. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Not authenticated. The bearer credential is missing, invalid, expired or already spent. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description No such resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    TransactionsController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted. No body. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation failed. `message` is the array of field errors produced by the global ValidationPipe. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Not authenticated. The bearer credential is missing, invalid, expired or already spent. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description No such resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    TransactionsController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTransactionDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionResponseDto"];
                };
            };
            /** @description Validation failed. `message` is the array of field errors produced by the global ValidationPipe. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Not authenticated. The bearer credential is missing, invalid, expired or already spent. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description No such resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    CategoriesController_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoriesResponseDto"];
                };
            };
            /** @description Not authenticated. The bearer credential is missing, invalid, expired or already spent. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    CategoriesController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCategoryDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryResponseDto"];
                };
            };
            /** @description Validation failed. `message` is the array of field errors produced by the global ValidationPipe. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Not authenticated. The bearer credential is missing, invalid, expired or already spent. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    CategoriesController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not authenticated. The bearer credential is missing, invalid, expired or already spent. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description No such resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description The request conflicts with the current state. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    CategoriesController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCategoryDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryResponseDto"];
                };
            };
            /** @description Validation failed. `message` is the array of field errors produced by the global ValidationPipe. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description Not authenticated. The bearer credential is missing, invalid, expired or already spent. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description No such resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description The request conflicts with the current state. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    DashboardController_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardResponseDto"];
                };
            };
            /** @description Not authenticated. The bearer credential is missing, invalid, expired or already spent. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    InsightsController_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InsightSetResponseDto"];
                };
            };
            /** @description Not authenticated. The bearer credential is missing, invalid, expired or already spent. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    InsightsController_generate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not authenticated. The bearer credential is missing, invalid, expired or already spent. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description The request conflicts with the current state. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
}
