/**
 * Turns the generated JSON into the two files `statistics.html` loads.
 *
 * ## Why the data is a script rather than a fetch
 *
 * The page is opened over `file://` from a laptop, possibly with no network in
 * the room. A page on `file://` **cannot `fetch` a sibling JSON file** - every
 * browser treats it as a cross-origin request to a null origin - so the data has
 * to arrive as executable JavaScript. `data/all.data.js` is one
 * `window.__SHOWCASE__ = {...}` assignment built from whatever `data/*.json`
 * currently holds.
 *
 * That split is what makes the refresh cheap: re-running the generators and
 * rewriting that one file is the whole of it, and the bundle below never has to
 * be rebuilt. Which matters, because the refresh happens minutes before the
 * talk and the bundle is the slow half.
 *
 * ## Why the bundle exists at all
 *
 * Recharts ships a UMD build that expects `React` as a global, and React 19
 * ships no UMD build at all - so a plain page loading both from disk renders a
 * blank chart area with no error worth reading. Bundling a small React entry
 * with esbuild sidesteps the whole question, and esbuild is already installed in
 * both apps, so this adds no dependency.
 *
 * **No CDN anywhere**, which is the point: the page must render identically on a
 * projector with the wifi off.
 *
 * ## Where the modules are resolved from
 *
 * `recharts` and `react` live in `frontend/node_modules` - they are the
 * frontend's dependencies, and this is deliberately the repo's own chart library
 * rather than a second one chosen for a slide. The entry file sits outside that
 * tree, so `nodePaths` points esbuild at it rather than moving a
 * showcase-only file into the app.
 */

import { existsSync, readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { DATA_DIR, REPO_ROOT } from './lib.mjs';

const SHOWCASE_DIR = join(REPO_ROOT, 'docs/showcase');
const ENTRY = join(REPO_ROOT, 'scripts/showcase/charts.jsx');
const BUNDLE = join(SHOWCASE_DIR, 'charts.js');

function writeDataScript() {
  const payload = {};

  for (const name of readdirSync(DATA_DIR).sort()) {
    if (!name.endsWith('.json')) {
      continue;
    }
    const key = name.replace(/\.json$/, '');
    payload[key] = JSON.parse(readFileSync(join(DATA_DIR, name), 'utf8'));
  }

  const path = join(DATA_DIR, 'all.data.js');
  writeFileSync(
    path,
    [
      '// Generated by scripts/showcase/build-charts.mjs. Do not edit.',
      '//',
      '// A script rather than a JSON fetch because this page is opened over',
      '// file://, where fetch of a sibling file is blocked.',
      `window.__SHOWCASE__ = ${JSON.stringify(payload, null, 2)};`,
      '',
    ].join('\n'),
  );

  console.log(`wrote ${path} (${Object.keys(payload).join(', ')})`);
}

async function bundle() {
  if (!existsSync(ENTRY)) {
    console.warn(`no chart entry at ${ENTRY}, skipping the bundle`);
    return;
  }

  const frontendModules = join(REPO_ROOT, 'frontend/node_modules');
  if (!existsSync(frontendModules)) {
    // A refresh on a machine that never installed the frontend still rewrites
    // the data; it just cannot rebuild the bundle, and the committed one stays.
    console.warn(
      'frontend/node_modules is missing, so the chart bundle was not rebuilt. ' +
        'The committed bundle is unchanged and the page still renders.',
    );
    return;
  }

  const { build } = await import(join(frontendModules, 'esbuild/lib/main.js'));

  await build({
    entryPoints: [ENTRY],
    outfile: BUNDLE,
    bundle: true,
    format: 'iife',
    minify: true,
    // React reads this to pick its production build; without it the bundle
    // carries the development one and warns into the console on a projector.
    define: { 'process.env.NODE_ENV': '"production"' },
    nodePaths: [frontendModules],
    logLevel: 'warning',
    jsx: 'automatic',
  });

  console.log(`wrote ${BUNDLE}`);
}

writeDataScript();
await bundle();
